### PR TITLE
Better content type detection for urls.

### PR DESCRIPTION
**Pull request by vangorra**
Uses the content type supplied by the server when

### CODE REVIEW

**Comment by dbashford** [comment]
Changing the signature for `fromFileWithPath` will likely break the tests and would at the very least require doc updates.  And I rather not complicate this.

Can you instead just add a `typeOverride` to the options object and use that?

**Comment by vangorra** [comment]
Good call! Here you go.

**Comment by dbashford** [comment]
Could you give me an idea of a file where the mime type wasn't being figured out properly? I can build a test around that later.

**Comment by vangorra** [comment]
Without this PR, mime.lookup uses the aspx extension to resolve an octet stream as the mimetype. Which textract will not parse. The following URL will demonstrate this.
http://apps.leg.wa.gov/billinfo/summary.aspx?bill=1276

**Comment by dbashford** [comment]
👍 

I'm deeply hoping to get another chunk of work done towards `2.0` this weekend.  I intend to merge this, but I want to do it when I'm ready to write a test or two for it.  So bear with me. =)

**Pull request merged**
